#!/usr/bin/env bash
#
# ~/.dotfiles/bash/bashrc

# Choose if to run Powerline prompt
export RUN_POWERLINE=false

# Load dotfiles
test -f ~/.dotfiles/bash/bash_dotfiles && . ~/.dotfiles/bash/bash_dotfiles
