#!/usr/bin/env bash
#
# ~/.bash/bash_user
# User specific environment


###############################
### Anaconda initialization ###
###############################

__conda_path="${HOME}/Software/miniconda3"

# >>> conda initialize >>>
# !! Contents within this block are managed by 'conda init' !!
__conda_setup="$('${__conda_path}/bin/conda' 'shell.bash' 'hook' 2> /dev/null)"
if [ $? -eq 0 ]; then
    eval "$__conda_setup"
else
    if [ -f "${__conda_path}/etc/profile.d/conda.sh" ]; then
        . "${__conda_path}/etc/profile.d/conda.sh"
    else
        export PATH="${__conda_path}/bin:${PATH}"
    fi
fi
unset __conda_setup __conda_path
# <<< conda initialize <<<


###########################
### Added by Travis gem ###
###########################

[[ ! -s ~/.travis/travis.sh ]] || . ~/.travis/travis.sh


#######################################################################
### Source VTE (Virtual Terminal Emulator)                          ###
### Reason: To report current directory for new tabs in Tilix       ###
### Reference: https://gnunn1.github.io/tilix-web/manual/vteconfig/ ###
#######################################################################

if [ $TILIX_ID ] || [ $VTE_VERSION ]; then
    . /etc/profile.d/vte.sh
fi


#######################################
### Cargo initialization (for Rust) ###
#######################################

test -f "$HOME/.cargo/env" && . "$HOME/.cargo/env"
