#!/usr/bin/env bash
#
# ~/.bash/bash_user
# User specific environment

###############################
### Anaconda initialization ###
###############################

if [[ -d "${INSTALLATION_CONDA}" ]]; then
    __conda_path="${INSTALLATION_CONDA}"

    # >>> conda initialize >>>
    # !! Contents within this block are managed by 'conda init' !!
    __conda_setup="$('${__conda_path}/bin/conda' 'shell.bash' 'hook' 2> /dev/null)"
    if [ $? -eq 0 ]; then
        eval "$__conda_setup"
    else
        if [ -f "${__conda_path}/etc/profile.d/conda.sh" ]; then
            . "${__conda_path}/etc/profile.d/conda.sh"
        else
            # Prevents double insertion
            # (see https://forums.opensuse.org/t/bashrc-sourced-twice/139123/3)
            if [[ :$PATH: != *:${__conda_path}/bin:* ]]; then
                export PATH="${__conda_path}/bin:${PATH}"
            fi
        fi
    fi
    unset __conda_setup __conda_path
    # <<< conda initialize <<<
fi


################################
### For the Powerline prompt ###
################################

if [[ "${ENABLE_POWERLINE}" == 'true' || "${ENABLE_POWERLINE}" == 1 ]]; then
    powerline-daemon -q
    POWERLINE_BASH_CONTINUATION=1
    POWERLINE_BASH_SELECT=1
    . /usr/share/powerline/bash/powerline.sh
fi


###########################
### Added by Travis gem ###
###########################

[[ ! -s ~/.travis/travis.sh ]] || . ~/.travis/travis.sh


#######################################################################
### Source VTE (Virtual Terminal Emulator)                          ###
### Reason: To report current directory for new tabs in Tilix       ###
### Reference: https://gnunn1.github.io/tilix-web/manual/vteconfig/ ###
#######################################################################

if [ $TILIX_ID ] || [ $VTE_VERSION ]; then
    . /etc/profile.d/vte.sh
fi


#######################################
### Cargo initialization (for Rust) ###
#######################################

test -f "${HOME}/.cargo/env" && . "${HOME}/.cargo/env"


#######################################
### Google Cloud SDK initialization ###
#######################################

if [[ -d "${INSTALLATION_GOOGLE_CLOUD_SDK}" ]]; then
    # Updates PATH for the Google Cloud SDK
    __file_to_be_sourced_1="${INSTALLATION_GOOGLE_CLOUD_SDK}/path.bash.inc"
    [[ -s "${__file_to_be_sourced_1}" ]] && . "${__file_to_be_sourced_1}"

    # Enables bash completion for gcloud
    __file_to_be_sourced_2="${INSTALLATION_GOOGLE_CLOUD_SDK}/completion.bash.inc"
    [[ -s "${__file_to_be_sourced_2}" ]] && . "${__file_to_be_sourced_2}"

    unset __file_to_be_sourced_1 __file_to_be_sourced_2
fi
