#!/usr/bin/env bash
#
# ~/.bash/bash_exports
# Load user-defined exports
# Based on: https://github.com/necolas/dotfiles/blob/master/shell/bash_exports

# Prevents double sourcing
if [[ -z "$BASH_EXPORTS_SOURCED" ]]; then
    export BASH_EXPORTS_SOURCED="yes"

    ##############
    ### System ###
    ##############

    # Ignore both spaces and duplicate commands in the history
    export HISTCONTROL=ignoreboth  # ignorespace + ignoredup

    # Increase the maximum number of lines contained in the history file, as
    # well the maximum number of commands to remember (default is 500 for both).
    # If you want infinite history, set them to anything < 0 (eg. -1).
    export HISTFILESIZE=10000  # lines
    export HISTSIZE=10000      # commands

    # History format
    export HISTTIMEFORMAT="%d/%m/%y %T "

    # Make the default editor
    export EDITOR="nano"
    export VISUAL="nano"

    # Make new shells get the history lines from all previous shells instead of
    # the default "last window closed" history.
    export PROMPT_COMMAND="history -a; ${PROMPT_COMMAND}"

    # Uncomment the following line if you don't like systemctl's auto-paging
    # feature:
    #export SYSTEMD_PAGER=


    ##########################
    ### User configuration ###
    ##########################

    if ! [[ "${PATH}" =~ ~/.local/bin:~/bin: ]]; then
        export PATH=~/.local/bin:~/bin:${PATH}
    fi


    ##########################################
    ### Variables to enable software usage ###
    ##########################################
    # Set them to the installation path of the given software, or either to 'true'
    # (case-insensitive) or 1 if the software was instaled system-wide.
    export ENABLE_CARGO='true'
    export ENABLE_CONDA="${HOME}/Software/miniconda3"
    export ENABLE_CUBA="${HOME}/Software/cuba"
    export ENABLE_FLUTTER="${HOME}/Software/development/flutter"
    export ENABLE_GO='true'
    export ENABLE_GOOGLE_CLOUD_SDK="${HOME}/Software/google-cloud-sdk"
    export ENABLE_MULTINEST="${HOME}/Software/MultiNest"
    export ENABLE_POWERLINE='true'
    export ENABLE_SPARK="${HOME}/Software/spark"
    export ENABLE_TRAVIS='false'


    ###################################
    ### Variables for several tools ###
    ###################################

    # For the Python language
    export PYTHONPATH=~/Projects/software/python

    # For the Go language
    if [[ "${ENABLE_GO}" == 'true' || "${ENABLE_GO}" == 1 ]]; then
        export GOPATH="${HOME}/Projects/software/go"
        export GOBIN="${GOPATH}/bin"
        export PATH="${GOBIN}:${PATH}"
    fi

    # For MultiNest and Cuba
    if [[ -n "${ENABLE_CUBA}" ]]; then
        export LD_LIBRARY_PATH="${ENABLE_CUBA}:${LD_LIBRARY_PATH}"
    fi
    if [[ -n "${ENABLE_MULTINEST}" ]]; then
        export LD_LIBRARY_PATH="${ENABLE_MULTINEST}/lib:${LD_LIBRARY_PATH}"
    fi

    # For Spark
    if [[ -n "${ENABLE_SPARK}" ]]; then
        export SPARK_HOME="${ENABLE_SPARK}"
        export PATH="${SPARK_HOME}/bin:${SPARK_HOME}/sbin:${PATH}"
    fi

    # For npm installs. See https://github.com/npm/npm/issues/8165#issuecomment-264002075.
    #export PATH=~/.npm-global/bin:${PATH}

    # For Miniconda
    #export LD_PRELOAD=~/Software/miniconda3/lib/libmkl_def.so:~/Software/miniconda3/lib/libmkl_avx2.so:${LD_PRELOAD}

    # For Flutter
    if [[ -n "${ENABLE_FLUTTER}" ]]; then
        export PATH="${ENABLE_FLUTTER}/bin:${PATH}"
    fi


    ###########################
    ### Setup in Manjaro OS ###
    ###########################

    # From .profile
    #export QT_QPA_PLATFORMTHEME="qt5ct"
    #export EDITOR=/usr/bin/nano

    # From .bashrc
    #export QT_SELECT=4
fi
