#!/bin/bash
#
# ~/.bash/bash_paths
# Load user-defined paths
# Based on: https://github.com/necolas/dotfiles/blob/master/shell/bash_paths

# Directories to be prepended to PATH
declare -a dirs_to_prepend=()
# Home paths
if ! [[ "${PATH}" =~ "${HOME}/.local/bin:${HOME}/bin": ]]; then
    dirs_to_prepend+=("${HOME}/.local/bin")
    dirs_to_prepend+=("${HOME}/bin")
fi
# For the Go language
if [[ -d "${GOBIN}" ]]; then
    dirs_to_prepend+=("${GOBIN}")
fi
# For Spark
if [[ -d "${SPARK_HOME}" ]]; then
    dirs_to_prepend+=("${SPARK_HOME}/bin")
    dirs_to_prepend+=("${SPARK_HOME}/sbin")
fi
# For Flutter
if [[ -d "${INSTALLATION_FLUTTER}" ]]; then
    dirs_to_prepend+=("${INSTALLATION_FLUTTER}/bin")
fi
# For npm installs. See https://github.com/npm/npm/issues/8165#issuecomment-264002075.
# dirs_to_prepend+=("${HOME}/.npm-global/bin")

# Directories to be appended to PATH
declare -a dirs_to_append=(
    # "{$HOME}/.dotfiles/bin"
)

# Prepend directories to PATH
for index in ${!dirs_to_prepend[*]}; do
    entry=${dirs_to_prepend[$index]}
    # If the directory is not in PATH yet and the directory exist, then prepend
    # it to existing PATH
    # (see https://forums.opensuse.org/t/bashrc-sourced-twice/139123/3).
    if [[ :$PATH: != *:$entry:* && -d "${entry}" ]]; then
        PATH="${entry}:${PATH}"
    fi
done

# Append directories to PATH
for index in ${!dirs_to_append[*]}; do
    entry=${dirs_to_append[$index]}
    # If the directory is not in PATH yet and the directory exist, then append
    # it to existing PATH
    # (see https://forums.opensuse.org/t/bashrc-sourced-twice/139123/3).
    if [[ :$PATH: != *:$entry:* && -d "${entry}" ]]; then
        PATH="${PATH}:${entry}"
    fi
done

unset dirs_to_prepend dirs_to_append entry

export PATH
