#!/usr/bin/env bash
#
# ~/.bash/bash_dotfiles
# Load dotfiles

load_dotfiles() {
    declare -a files=(
        ~/.bash/bash_options  # Options
        ~/.bash/bash_aliases  # Aliases
        ~/.bash/functions/*   # Functions
        ~/.bash/bash_user     # User environment
        ~/.bash/bash_prompt   # Custom bash prompt
        ~/.bash/bash_paths    # Path modifications
        ~/.bash_profile.local # Local/private settings not under version control (e.g. git credentials)
    )

    # If these files are readable, source them
    for index in ${!files[*]}; do
        test -r "${files[$index]}" && . "${files[$index]}"
    done
}

echo "[bash_dotfiles]      BASH_EXPORTS_SOURCED=$BASH_EXPORTS_SOURCED"

# Sourcing `bash_exports` before the other Bash files due to its double
# sourcing prevention method. Tip from https://unix.stackexchange.com/a/425759.
# if [[ "${BASH_EXPORTS_SOURCED}" != "yes" && -f "${HOME}/.bash/bash_exports" ]]
# then
if [[ -f "${HOME}/.bash/bash_exports" ]]; then
    . "${HOME}/.bash/bash_exports"  # Exports
fi

load_dotfiles
unset load_dotfiles
