#!/usr/bin/env bash
#
# ~/.bash/bash_exports
# Load user-defined exports
# Based on: https://github.com/necolas/dotfiles/blob/master/shell/bash_exports

# Prevents double sourcing
if [[ -z "$BASH_EXPORTS_SOURCED" ]]; then
    export BASH_EXPORTS_SOURCED="yes"

    ##############
    ### System ###
    ##############

    # Make the default editor
    export EDITOR="nano"
    export VISUAL="nano"

    # Make new shells get the history lines from all previous shells instead of
    # the default "last window closed" history.
    export PROMPT_COMMAND="history -a; ${PROMPT_COMMAND}"

    # Uncomment the following line if you don't like systemctl's auto-paging
    # feature:
    #export SYSTEMD_PAGER=


    ##########################
    ### User configuration ###
    ##########################

    if ! [[ "${PATH}" =~ ~/.local/bin:~/bin: ]]; then
        export PATH=~/.local/bin:~/bin:${PATH}
    fi


    ###################################
    ### Variables for several tools ###
    ###################################

    # For the Python language
    export PYTHONPATH=~/Projects/software/python

    # For the Go language
    export GOPATH=~/Projects/software/go
    export GOBIN="${GOPATH}/bin"
    export PATH="${GOBIN}:${PATH}"

    # For MultiNest and Cuba
    #export LD_LIBRARY_PATH=~/Software/MultiNest/lib:~/Software/cuba:${LD_LIBRARY_PATH}

    # For Spark
    export SPARK_HOME=~/Software/spark
    export PATH=${SPARK_HOME}/bin:${SPARK_HOME}/sbin:${PATH}

    # For npm installs. See https://github.com/npm/npm/issues/8165#issuecomment-264002075.
    #export PATH=~/.npm-global/bin:${PATH}

    #export PATH=~/.cargo/bin:${PATH}

    # For Miniconda
    #export LD_PRELOAD=~/Software/miniconda3/lib/libmkl_def.so:~/Software/miniconda3/lib/libmkl_avx2.so:${LD_PRELOAD}

    # For Google Cloud
    #. ~/Software/google-cloud-sdk/path.bash.inc  # Updates PATH for the Google Cloud SDK
    #. ~/Software/google-cloud-sdk/completion.bash.inc  # Enables bash completion for gcloud


    ###############
    ### History ###
    ###############

    # Ignore both spaces and duplicate commands in the history
    export HISTCONTROL=ignoreboth  # ignorespace + ignoredup

    # Increase the maximum number of lines contained in the history file, as
    # well the maximum number of commands to remember (default is 500 for both).
    # If you want infinite history, set them to anything < 0 (eg. -1).
    export HISTFILESIZE=10000  # lines
    export HISTSIZE=10000      # commands

    # History format
    export HISTTIMEFORMAT="%d/%m/%y %T "


    ###########################
    ### Setup in Manjaro OS ###
    ###########################

    # From .profile
    #export QT_QPA_PLATFORMTHEME="qt5ct"
    #export EDITOR=/usr/bin/nano

    # From .bashrc
    #export QT_SELECT=4
fi
