#!/usr/bin/env bash
#
# ~/.bash/functions/colors2
# Source: https://unix.stackexchange.com/a/521120

colors2() {
    # Connector fifos directory
    read TMPDIR < <(mktemp -d /dev/shm/conn_shell_XXXXXXX)

    fd=3
    # find next free fd
    nextFd() { while [ -e /dev/fd/$fd ]; do ((fd++)); done; printf -v $1 %d $fd; }

    tputConnector() {
        mkfifo $TMPDIR/tput
        nextFd TPUTIN
        eval "exec $TPUTIN> >(LANG=C exec stdbuf -o0 tput -S - >$TMPDIR/tput 2>&1)"
        nextFd TPUTOUT
        eval "exec $TPUTOUT<$TMPDIR/tput"
        rm $TMPDIR/tput
        rmdir $TMPDIR
    }

    myTput() {
        echo -e "$1\ncr" 1>&$TPUTIN && IFS= read -r -d $'\r' -u $TPUTOUT $2
    }
    tputConnector

    myTput op op
    myTput "setaf 7" grey
    myTput "setaf 16" black
    fore=("$black" "$grey")
    for ((i=0; i<256; i++)); do
        myTput "setab $i" bgr
        printf "  %s%s  %3d  %s" "$bgr" "${fore[ i>231 && i<244||(i<17)&& (i%8<2)||
            (i>16&&i<232)&&((i-16)%6*11+(i-16)/6%6*14+(i-16)/36*10)<58
            ? 1 : 0 ]}" $i "$op"
        (( ((i<16||i>231) && ((i+1)%8==0)) || ((i>16&&i<232)&& ((i-15)%6==0)) )) &&
            printf "\n" ''
    done
}
